Repository ritik-369/Hacktoberfest-Projects-2022, pull requests merged in 2022-10, with the labels that each got.

#29 Create bubble_sort.py
  Algorithms/Python/sorting/bubble_sort.py
Labels: enhancement, hacktoberfest-accepted

#31 Shopping Cart using LinkList
  Projects/Programming_language_projects/C/Shopping Cart using LinkList.c
Labels: enhancement, hacktoberfest-accepted

#39 Create remove_duplicates.py
  Algorithms/Python/data_structures/remove_duplicates.py
Labels: hacktoberfest-accepted, python

#47 Create find smallest number in a list
  Algorithms/Python/data_structures/find smallest number in a list
Labels: enhancement, hacktoberfest-accepted, python

#37 Add binarySearch in 2D row column wise sorted matrix
  Algorithms/C/searching/search2DMatrix.cpp
Labels: hacktoberfest-accepted, C++

#50 created heap sort in C++ using DP
  Algorithms/C++/sorting/Heapsort.cpp
Labels: enhancement, hacktoberfest-accepted, C++

#53 Added programs in trees and data_structures
  Algorithms/C/data_structures/Linked List/10_insertinginsorted.c
  Algorithms/C/data_structures/Linked List/11_deletingnode.c
  Algorithms/C/data_structures/Linked List/12_checksorting.c
  Algorithms/C/data_structures/Linked List/13_removeduplicates.c
  Algorithms/C/data_structures/Linked List/14_reversinglist.c
  Algorithms/C/data_structures/Linked List/15_concatenation.c
  Algorithms/C/data_structures/Linked List/16_merginglists.c
  Algorithms/C/data_structures/Linked List/17_loopcheck.c
  Algorithms/C/data_structures/Linked List/18_circularlinkedlist.c
  Algorithms/C/data_structures/Linked List/19_insertingincircularlinkedlist.c
  Algorithms/C/data_structures/Linked List/1makinglinkedlist.c
  Algorithms/C/data_structures/Linked List/20_deletingincircularLL.c
  Algorithms/C/data_structures/Linked List/21_doublelinkedlist.c
  Algorithms/C/data_structures/Linked List/22_insertingindoubleLL.c
  Algorithms/C/data_structures/Linked List/23_reversedoubleLL.c
  Algorithms/C/data_structures/Linked List/24_polynomial.c
  Algorithms/C/data_structures/Linked List/25_polynomialaddition.c
  Algorithms/C/data_structures/Linked List/26_polynomialmultiplication.c
  Algorithms/C/data_structures/Linked List/27_sortingLL.c
  Algorithms/C/data_structures/Linked List/2displayinglinkedlist.c
  Algorithms/C/data_structures/Linked List/3countingnodes.c
  Algorithms/C/data_structures/Linked List/4_sumofallelements.c
  Algorithms/C/data_structures/Linked List/5_maximumelement.c
  Algorithms/C/data_structures/Linked List/6_searchinginlinkedlist.c
  Algorithms/C/data_structures/Linked List/7_improvingsearching.c
  Algorithms/C/data_structures/Linked List/8_insertingnode.c
  Algorithms/C/data_structures/Linked List/9_insertlast.c
  Algorithms/C/data_structures/Queues/1_queuesusingarray.c
  Algorithms/C/data_structures/Queues/2_circularqueue.c
  Algorithms/C/data_structures/Queues/3_queueusingLL.c
  Algorithms/C/data_structures/Queues/4_DEqueue.c
  Algorithms/C/data_structures/Queues/5_priority_queue.c
  Algorithms/C/data_structures/Queues/6_queue_using_stacks.c
  Algorithms/C/data_structures/Queues/7_overlapping_queues.c
  Algorithms/C/data_structures/Stacks/1_stacksusingarray.c
  Algorithms/C/data_structures/Stacks/2_stackusingLL.c
  Algorithms/C/data_structures/Stacks/4_paranthesismatching.c
  Algorithms/C/data_structures/Stacks/5_infixtopostfix.c
  Algorithms/C/data_structures/Stacks/6_evaluationofpostfix.c
  Algorithms/C/data_structures/Stacks/7_tower_of_hanoi.c
  Algorithms/C/data_structures/Stacks/8_overlapping_stacks.c
  Algorithms/C/data_structures/Stacks/9_postfixtoinfix.c
  Algorithms/C/trees/BinarySearchTree.c
  Algorithms/C/trees/CountinginBinaryTree.c
  Algorithms/C/trees/CreatingBinaryTree.c
Labels: enhancement, hacktoberfest-accepted

#55 Create Counting_Sort.cpp
  Algorithms/C++/others/fabonacci.cpp
  Algorithms/C++/others/palindromenumber.cpp
  Algorithms/C++/others/primebtwn2no.cpp
  Algorithms/C++/sorting/countingsort.cpp
  Algorithms/C++/sorting/merge_sort.cpp
Labels: enhancement, hacktoberfest-accepted, C++

#56 Create InsertionSort.java
  Algorithms/Java/sorting/InsertionSort.java
Labels: enhancement, hacktoberfest-accepted, java

#57 Matchstick_Game
  Projects/Programming_language_projects/C/matchstickgame.c
Labels: enhancement, hacktoberfest-accepted, C

#58 Added Patterns.py in Python Folder
  Algorithms/Python/Patterns/Patterns.py
Labels: enhancement, hacktoberfest-accepted, python

#64 Tic-tac-toe using Python
  Projects/Programming_language_projects/Python/Multiplayer.py
  Projects/Programming_language_projects/Python/PythonProject.zip
  Projects/Programming_language_projects/Python/SinglePlayer.cpython-39.pyc
  Projects/Programming_language_projects/Python/SinglePlayer.py
  Projects/Programming_language_projects/Python/TicTacToe.py
  Projects/Programming_language_projects/Python/tempCodeRunnerFile.py
Labels: enhancement, hacktoberfest-accepted, python

#60 Structure and Enum code is added
  Algorithms/C/geometry/Boxes_Struct_Enums.c
Labels: enhancement, hacktoberfest-accepted, C

#61 added files for a project "simple-weather-app"
  Projects/WEB_PROJECT/Simple-Weather-App/README.md
  Projects/WEB_PROJECT/Simple-Weather-App/bg.jpg
  Projects/WEB_PROJECT/Simple-Weather-App/favicon.ico
  Projects/WEB_PROJECT/Simple-Weather-App/index.html
  Projects/WEB_PROJECT/Simple-Weather-App/main.css
  Projects/WEB_PROJECT/Simple-Weather-App/main.js
Labels: enhancement, hacktoberfest-accepted
